#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v16
# autospec commit: b858a2a
#
Name     : R-RPushbullet
Version  : 0.3.4
Release  : 3
URL      : https://cran.r-project.org/src/contrib/RPushbullet_0.3.4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/RPushbullet_0.3.4.tar.gz
Summary  : R Interface to the Pushbullet Messaging Service
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-curl
Requires: R-jsonlite
BuildRequires : R-curl
BuildRequires : R-jsonlite
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
provides fast and efficient notifications (and file transfer) between
 computers, phones and tablets.  An account has to be registered at the

%prep
%setup -q -n RPushbullet

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1721073854

%install
export SOURCE_DATE_EPOCH=1721073854
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/RPushbullet/DESCRIPTION
/usr/lib64/R/library/RPushbullet/INDEX
/usr/lib64/R/library/RPushbullet/Meta/Rd.rds
/usr/lib64/R/library/RPushbullet/Meta/features.rds
/usr/lib64/R/library/RPushbullet/Meta/hsearch.rds
/usr/lib64/R/library/RPushbullet/Meta/links.rds
/usr/lib64/R/library/RPushbullet/Meta/nsInfo.rds
/usr/lib64/R/library/RPushbullet/Meta/package.rds
/usr/lib64/R/library/RPushbullet/NAMESPACE
/usr/lib64/R/library/RPushbullet/NEWS.Rd
/usr/lib64/R/library/RPushbullet/R/RPushbullet
/usr/lib64/R/library/RPushbullet/R/RPushbullet.rdb
/usr/lib64/R/library/RPushbullet/R/RPushbullet.rdx
/usr/lib64/R/library/RPushbullet/help/AnIndex
/usr/lib64/R/library/RPushbullet/help/RPushbullet.rdb
/usr/lib64/R/library/RPushbullet/help/RPushbullet.rdx
/usr/lib64/R/library/RPushbullet/help/aliases.rds
/usr/lib64/R/library/RPushbullet/help/paths.rds
/usr/lib64/R/library/RPushbullet/html/00Index.html
/usr/lib64/R/library/RPushbullet/html/R.css
/usr/lib64/R/library/RPushbullet/tests/simpleTests.R
